name: Generate RM PDF from given URL

on:
  workflow_dispatch:
    inputs:
      url:
        description: URL to epub / PDF file
        required: true
        type: string

jobs:
  generate-rm-pdf-and-publish:
    runs-on: ubuntu-latest
    container:
      image: linuxserver/calibre:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Mask Input URL for logs
        run: |
          API_INPUT_URL=$(jq -r '.inputs.url' $GITHUB_EVENT_PATH)
          echo API_INPUT_URL="$API_INPUT_URL" >> $GITHUB_ENV
          echo ::add-mask::$API_INPUT_URL
      - name: Generate RM PDF (from URL input)
        env:
          RM_CONFIG: ${{ secrets.RM_CONFIG }}
        run: |
          OUTPUT_PATTERN="*-$(date '+%d.%m.%Y').pdf"
          ./generate-rm-pdf.sh "$API_INPUT_URL"
          ./publish-to-rm.sh "$OUTPUT_PATTERN" /Github/
